### PR TITLE
Added open source information and fixed ampersands

### LINKED ISSUE #1269: Talk more about why open source is awesome
On the open source page we should talk more about why open source rocks and why we choose open source.

### PR DESCRIPTION
**Pull request by tehp**
Fixes #1269 

### Changes Summary

- Added copy from #1269 
- Fixed ampersands in a few files

This pull request [ is ] ready for review.

### CODE REVIEW

File: open-source.php [hunk 1]
```diff
@@ -15,7 +15,24 @@
     <div class="two-thirds">
         <h1>We're Built on Open Source</h1>
         <h4>The elementary OS platform is built upon a strong foundation of Free &amp; Open Source software. Without projects such as these, elementary OS would not exist.</h4>
+        </div>
+        <div class="half">
+        <h3>Security &amp; Privacy</h3>
```
Comment (cassidyjames) [inline open-source.php]: Indentation looks off starting here. Our code style is 4 spaces.

File: open-source.php [hunk 2]
```diff
@@ -15,7 +15,24 @@
...
+          <h4>By being Open Source, elementary OS can benefit from superior security and privacy over closed source software. When the source code is available to audit, anyone in the community — whether a security researcher, a concerned user, or an OEM shipping the OS on their hardware — can ensure the software is secure and not collecting or leaking personal information.</h4>
+        </div>
+        <div class="half">
+          <div>
```
Comment (cassidyjames) [inline open-source.php]: Extra wrapper div in here?

**Comment by cassidyjames** [comment]
The ampersand changes and copy itself look good, just some indentation weirdness I think.

File: open-source.php [hunk 3]
```diff
@@ -15,7 +15,21 @@
     <div class="two-thirds">
         <h1>We're Built on Open Source</h1>
         <h4>The elementary OS platform is built upon a strong foundation of Free &amp; Open Source software. Without projects such as these, elementary OS would not exist.</h4>
-        <a class="button suggested-action" href="get-involved#desktop-development">Get Involved</a>
+    </div>
+    <div class="half">
+        <h3>Security &amp; Privacy</h3>
+        <h4>By being Open Source, elementary OS can benefit from superior security and privacy over closed source software. When the source code is available to audit, anyone in the community — whether a security researcher, a concerned user, or an OEM shipping the OS on their hardware — can ensure the software is secure and not collecting or leaking personal information.</h4>
```
Comment (cassidyjames) [inline open-source.php]: Switch to a `<p>`

File: open-source.php [hunk 4]
```diff
@@ -15,7 +15,21 @@
...
+    </div>
+    <div class="half">
+        <h3>Better for Developers</h3>
+        <h4>If your app could benefit from a system API or feature that’s not yet available, you can help write that feature into the OS. Similarly, you might be curious as to how a feature or design pattern in elementary OS was made. Instead of guessing or trying to reimplement it on your own, you can just look at the underlying source code for a definitive answer.</h4>
```
Comment (cassidyjames) [inline open-source.php]: Switch to a `<p>`

File: open-source.php [hunk 5]
```diff
@@ -15,7 +15,21 @@
...
+    </div>
+    <a class="button suggested-action" href="get-involved#desktop-development">Get Involved</a>
+    <div class="whole">
+        <div class="two-thirds">
+            <h2>We Support Open Source Projects</h2>
```
Comment (cassidyjames) [inline open-source.php]: It looks like this block got copied in up here when it's already down below.
