### PR TITLE
Fix broken cookie behavior #1451

### LINKED ISSUE #1451: Button still says "Purchase elementary OS" on subsequent visits.
### Expected behavior

The button says "Download elementary OS" if it detects the visitor has paid on an earlier visit.

### Actual behavior

The button says "Purchase elementary OS"

### Steps to reproduce the behavior

1. Purchase elementary OS, or set the cookie like [`backend/payment.php#L24`](https://github.com/elementary/website/blob/master/backend/payment.php#L24)
2. Visit the main page

### PR DESCRIPTION
**Pull request by lewisgoddard**
Fixes #1451

### Changes Summary

- Remove character stripping that we don't use any more when setting the cookie.

This pull request is ready for review.

### CODE REVIEW

File: index.php [hunk 1]
```diff
@@ -42,8 +42,7 @@
                 <div id="amounts">
                     <?php
                         $paidString = 'has_paid_'.$config['release_title'].'_'.$config['release_version'];
-                        $disallowed = [' ', '.'];
-                        $encoded = urlencode(str_replace($disallowed, '_', $paidString));
+                        $encoded = urlencode($disallowed, '_', $paidString);
```
Comment (btkostner) [inline index.php]: You are referencing `$disallowed` but you removed the line defining it. Sure you didn't mean `urlencode($paidString);`?
